version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ..:/var/www/nean.io:ro
  #     - ${ROOT_DIR}/nginx/conf.d/:/etc/nginx/conf.d/:ro
  #     # - ${ROOT_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ${ROOT_DIR}/nginx/plugins.d/:/etc/nginx/plugins.d/:ro
  #     - ${ROOT_DIR}/nginx/sites-enabled.d/:/etc/nginx/sites-enabled.d/:ro
  #     - ${ROOT_DIR}/nginx/ssl/:/etc/nginx/ssl/:ro
  #     - ${ROOT_DIR}/nginx/log:/dev/log

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com 

  neo4j:
    container_name: neo4j
    image: neo4j:4.0-enterprise
    ports:
      - "7474:7474"  ## Browser
      - "7687:7687"  ## Bolt connection
    volumes:
      - ${ROOT_DIR}/neo4j/data:/data
      - ${ROOT_DIR}/neo4j/backup:/backup
      - ${ROOT_DIR}/neo4j/plugins:/plugins
    environment:
      NEO4J_dbms_memory_heap_max__size: "512M"
      NEO4J_dbms_memory_pagecache_size: "512M"
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
      - ${ROOT_DIR}/rabbitmq/logs/:/var/log/rabbitmq/
      # - ${ROOT_DIR}/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

  countly:
    container_name: countly
    image: countly/countly-server
    ports:
      - "32768:80"
    volumes:
      - ${ROOT_DIR}/countly:/data/db
    restart: unless-stopped