module.exports = {
    NODE_ENV: 'development',
    PORT: 3000,
    NEO4J_URI: 'neo4j://localhost',
    NEO4J_NAME: 'nean',
    NEO4J_ADMIN_USERNAME: 'neo4j',
    NEO4J_ADMIN_PASSWORD: 'password',
    NEO4J_USERNAME: 'server_api',
    NEO4J_PASSWORD: 'password',
    RABBITMQ_VIRTUAL_HOST: 'nean',
    RABBITMQ_ADMIN_USERNAME: 'guest',
    RABBITMQ_ADMIN_PASSWORD: 'guest',
    RABBITMQ_USERNAME: 'server_api',
    RABBITMQ_PASSWORD: 'password',
    RABBITMQ_PORT: 5672,
    STRIPE_KEY: 'sk_test_RKOxhujxxM8c4xIqt6t036Qo',
    AUTHENTICATION_KEY: '37LvDSm4XvjYOh9Y',
}