export interface TimeZoneGroup {
    name: string;
    zones: Array<TimeZone>;
}

export interface TimeZone {
    zone: string;
    type: string;
    name: string;
}

// https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
export const timeZones: Array<TimeZoneGroup> = [
    {
        name: 'Africa',
        zones: [
            { zone: '+00:00', type: 'Canonical', name: 'Abidjan' },
            { zone: '+00:00', type: 'Canonical', name: 'Accra' },
            { zone: '+03:00', type: 'Alias', name: 'Addis Ababa' },
            { zone: '+01:00', type: 'Canonical', name: 'Algiers' },
            { zone: '+03:00', type: 'Alias', name: 'Asmara' },
            { zone: '+00:00', type: 'Alias', name: 'Bamako' },
            { zone: '+01:00', type: 'Alias', name: 'Bangui' },
            { zone: '+00:00', type: 'Alias', name: 'Banjul' },
            { zone: '+00:00', type: 'Canonical', name: 'Bissau' },
            { zone: '+02:00', type: 'Alias', name: 'Blantyre' },
            { zone: '+01:00', type: 'Alias', name: 'Brazzaville' },
            { zone: '+02:00', type: 'Alias', name: 'Bujumbura' },
            { zone: '+02:00', type: 'Canonical', name: 'Cairo' },
            { zone: '+01:00', type: 'Canonical', name: 'Casablanca' },
            { zone: '+01:00', type: 'Canonical', name: 'Ceuta' },
            { zone: '+00:00', type: 'Alias', name: 'Conakry' },
            { zone: '+00:00', type: 'Alias', name: 'Dakar' },
            { zone: '+03:00', type: 'Alias', name: 'Dar es Salaam' },
            { zone: '+03:00', type: 'Alias', name: 'Djibouti' },
            { zone: '+01:00', type: 'Alias', name: 'Douala' },
            { zone: '+00:00', type: 'Canonical', name: 'El Aaiun' },
            { zone: '+00:00', type: 'Alias', name: 'Freetown' },
            { zone: '+02:00', type: 'Alias', name: 'Gaborone' },
            { zone: '+02:00', type: 'Alias', name: 'Harare' },
            { zone: '+02:00', type: 'Canonical', name: 'Johannesburg' },
            { zone: '+03:00', type: 'Canonical', name: 'Juba' },
            { zone: '+03:00', type: 'Alias', name: 'Kampala' },
            { zone: '+02:00', type: 'Canonical', name: 'Khartoum' },
            { zone: '+02:00', type: 'Alias', name: 'Kigali' },
            { zone: '+01:00', type: 'Alias', name: 'Kinshasa' },
            { zone: '+01:00', type: 'Canonical', name: 'Lagos' },
            { zone: '+01:00', type: 'Alias', name: 'Libreville' },
            { zone: '+00:00', type: 'Alias', name: 'Lome' },
            { zone: '+01:00', type: 'Alias', name: 'Luanda' },
            { zone: '+02:00', type: 'Alias', name: 'Lubumbashi' },
            { zone: '+02:00', type: 'Alias', name: 'Lusaka' },
            { zone: '+01:00', type: 'Alias', name: 'Malabo' },
            { zone: '+02:00', type: 'Canonical', name: 'Maputo' },
            { zone: '+02:00', type: 'Alias', name: 'Maseru' },
            { zone: '+02:00', type: 'Alias', name: 'Mbabane' },
            { zone: '+03:00', type: 'Alias', name: 'Mogadishu' },
            { zone: '+00:00', type: 'Canonical', name: 'Monrovia' },
            { zone: '+03:00', type: 'Canonical', name: 'Nairobi' },
            { zone: '+01:00', type: 'Canonical', name: 'Ndjamena' },
            { zone: '+01:00', type: 'Alias', name: 'Niamey' },
            { zone: '+00:00', type: 'Alias', name: 'Nouakchott' },
            { zone: '+00:00', type: 'Alias', name: 'Ouagadougou' },
            { zone: '+01:00', type: 'Alias', name: 'Porto' },
            { zone: '+00:00', type: 'Alias', name: 'Sao Tome' },
            { zone: '+00:00', type: 'Alias', name: 'Timbuktu' },
            { zone: '+02:00', type: 'Canonical', name: 'Tripoli' },
            { zone: '+01:00', type: 'Canonical', name: 'Tunis' },
            { zone: '+02:00', type: 'Canonical', name: 'Windhoekk' }
        ]
    },
    {
        name: 'America',
        zones: [
            { zone: '-10:00', type: 'Canonical', name: 'Adak' },
            { zone: '-09:00', type: 'Canonical', name: 'Anchorage' },
            { zone: '-04:00', type: 'Alias', name: 'Anguilla' },
            { zone: '-04:00', type: 'Alias', name: 'Antigua' },
            { zone: '-03:00', type: 'Canonical', name: 'Araguaina' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Buenos Aires' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Catamarca' },
            { zone: '-03:00', type: 'Alias', name: 'Argentina/ComodRivadavia' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Cordoba' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Jujuy' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/La Rioja' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Mendoza' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Rio Gallegos' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Salta' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/San Juan' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/San Luis' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Tucuman' },
            { zone: '-03:00', type: 'Canonical', name: 'Argentina/Ushuaia' },
            { zone: '-04:00', type: 'Alias', name: 'Aruba' },
            { zone: '-04:00', type: 'Canonical', name: 'Asuncion' },
            { zone: '-05:00', type: 'Canonical', name: 'Atikokan' },
            { zone: '-10:00', type: 'Alias', name: 'Atka' },
            { zone: '-03:00', type: 'Canonical', name: 'Bahia' },
            { zone: '-06:00', type: 'Canonical', name: 'Bahia Banderas' },
            { zone: '-04:00', type: 'Canonical', name: 'Barbados' },
            { zone: '-03:00', type: 'Canonical', name: 'Belem' },
            { zone: '-06:00', type: 'Canonical', name: 'Belize' },
            { zone: '-04:00', type: 'Canonical', name: 'Blanc' },
            { zone: '-04:00', type: 'Canonical', name: 'Boa Vista' },
            { zone: '-05:00', type: 'Canonical', name: 'Bogota' },
            { zone: '-07:00', type: 'Canonical', name: 'Boise' },
            { zone: '-03:00', type: 'Alias', name: 'Buenos Aires' },
            { zone: '-07:00', type: 'Canonical', name: 'Cambridge Bay' },
            { zone: '-04:00', type: 'Canonical', name: 'Campo Grande' },
            { zone: '-05:00', type: 'Canonical', name: 'Cancun' },
            { zone: '-04:00', type: 'Canonical', name: 'Caracas' },
            { zone: '-03:00', type: 'Alias', name: 'Catamarca' },
            { zone: '-03:00', type: 'Canonical', name: 'Cayenne' },
            { zone: '-05:00', type: 'Alias', name: 'Cayman' },
            { zone: '-06:00', type: 'Canonical', name: 'Chicago' },
            { zone: '-07:00', type: 'Canonical', name: 'Chihuahua' },
            { zone: '-05:00', type: 'Alias', name: 'Coral Harbour' },
            { zone: '-03:00', type: 'Alias', name: 'Cordoba' },
            { zone: '-06:00', type: 'Canonical', name: 'Costa Rica' },
            { zone: '-07:00', type: 'Canonical', name: 'Creston' },
            { zone: '-04:00', type: 'Canonical', name: 'Cuiaba' },
            { zone: '-04:00', type: 'Canonical', name: 'Curacao' },
            { zone: '+00:00', type: 'Canonical', name: 'Danmarkshavn' },
            { zone: '-08:00', type: 'Canonical', name: 'Dawson' },
            { zone: '-07:00', type: 'Canonical', name: 'Dawson Creek' },
            { zone: '-07:00', type: 'Canonical', name: 'Denver' },
            { zone: '-05:00', type: 'Canonical', name: 'Detroit' },
            { zone: '-04:00', type: 'Alias', name: 'Dominica' },
            { zone: '-07:00', type: 'Canonical', name: 'Edmonton' },
            { zone: '-05:00', type: 'Canonical', name: 'Eirunepe' },
            { zone: '-06:00', type: 'Canonical', name: 'El Salvador' },
            { zone: '-08:00', type: 'Alias', name: 'Ensenada' },
            { zone: '-07:00', type: 'Canonical', name: 'Fort Nelson' },
            { zone: '-05:00', type: 'Alias', name: 'Fort Wayne' },
            { zone: '-03:00', type: 'Canonical', name: 'Fortaleza' },
            { zone: '-04:00', type: 'Canonical', name: 'Glace Bay' },
            { zone: '-03:00', type: 'Canonical', name: 'Godthab' },
            { zone: '-04:00', type: 'Canonical', name: 'Goose Bay' },
            { zone: '-05:00', type: 'Canonical', name: 'Grand Turk' },
            { zone: '-04:00', type: 'Alias', name: 'Grenada' },
            { zone: '-04:00', type: 'Alias', name: 'Guadeloupe' },
            { zone: '-06:00', type: 'Canonical', name: 'Guatemala' },
            { zone: '-05:00', type: 'Canonical', name: 'Guayaquil' },
            { zone: '-04:00', type: 'Canonical', name: 'Guyana' },
            { zone: '-04:00', type: 'Canonical', name: 'Halifax' },
            { zone: '-05:00', type: 'Canonical', name: 'Havana' },
            { zone: '-07:00', type: 'Canonical', name: 'Hermosillo' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Indianapolis' },
            { zone: '-06:00', type: 'Canonical', name: 'Indiana/Knox' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Marengo' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Petersburg' },
            { zone: '-06:00', type: 'Canonical', name: 'Indiana/Tell City' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Vevay' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Vincennes' },
            { zone: '-05:00', type: 'Canonical', name: 'Indiana/Winamac' },
            { zone: '-05:00', type: 'Alias', name: 'Indianapolis' },
            { zone: '-07:00', type: 'Canonical', name: 'Inuvik' },
            { zone: '-05:00', type: 'Canonical', name: 'Iqaluit' },
            { zone: '-05:00', type: 'Canonical', name: 'Jamaica' },
            { zone: '-03:00', type: 'Alias', name: 'Jujuy' },
            { zone: '-09:00', type: 'Canonical', name: 'Juneau' },
            { zone: '-05:00', type: 'Canonical', name: 'Kentucky/Louisville' },
            { zone: '-05:00', type: 'Canonical', name: 'Kentucky/Monticello' },
            { zone: '-06:00', type: 'Alias', name: 'Knox IN' },
            { zone: '-04:00', type: 'Alias', name: 'Kralendijk' },
            { zone: '-04:00', type: 'Canonical', name: 'La Paz' },
            { zone: '-05:00', type: 'Canonical', name: 'Lima' },
            { zone: '-08:00', type: 'Canonical', name: 'Los Angeles' },
            { zone: '-05:00', type: 'Alias', name: 'Louisville' },
            { zone: '-04:00', type: 'Alias', name: 'Lower Princes' },
            { zone: '-03:00', type: 'Canonical', name: 'Maceio' },
            { zone: '-06:00', type: 'Canonical', name: 'Managua' },
            { zone: '-04:00', type: 'Canonical', name: 'Manaus' },
            { zone: '-04:00', type: 'Alias', name: 'Marigot' },
            { zone: '-04:00', type: 'Canonical', name: 'Martinique' },
            { zone: '-06:00', type: 'Canonical', name: 'Matamoros' },
            { zone: '-07:00', type: 'Canonical', name: 'Mazatlan' },
            { zone: '-03:00', type: 'Alias', name: 'Mendoza' },
            { zone: '-06:00', type: 'Canonical', name: 'Menominee' },
            { zone: '-06:00', type: 'Canonical', name: 'Merida' },
            { zone: '-09:00', type: 'Canonical', name: 'Metlakatla' },
            { zone: '-06:00', type: 'Canonical', name: 'Mexico City' },
            { zone: '-03:00', type: 'Canonical', name: 'Miquelon' },
            { zone: '-04:00', type: 'Canonical', name: 'Moncton' },
            { zone: '-06:00', type: 'Canonical', name: 'Monterrey' },
            { zone: '-03:00', type: 'Canonical', name: 'Montevideo' },
            { zone: '-05:00', type: 'Alias', name: 'Montreal' },
            { zone: '-04:00', type: 'Alias', name: 'Montserrat' },
            { zone: '-05:00', type: 'Canonical', name: 'Nassau' },
            { zone: '-05:00', type: 'Canonical', name: 'New York' },
            { zone: '-05:00', type: 'Canonical', name: 'Nipigon' },
            { zone: '-09:00', type: 'Canonical', name: 'Nome' },
            { zone: '-02:00', type: 'Canonical', name: 'Noronha' },
            { zone: '-06:00', type: 'Canonical', name: 'North Dakota/Beulah' },
            { zone: '-06:00', type: 'Canonical', name: 'North Dakota/Center' },
            { zone: '-06:00', type: 'Canonical', name: 'North Dakota/New Salem' },
            { zone: '-07:00', type: 'Canonical', name: 'Ojinaga' },
            { zone: '-05:00', type: 'Canonical', name: 'Panama' },
            { zone: '-05:00', type: 'Canonical', name: 'Pangnirtung' },
            { zone: '-03:00', type: 'Canonical', name: 'Paramaribo' },
            { zone: '-07:00', type: 'Canonical', name: 'Phoenix' },
            { zone: '-04:00', type: 'Canonical', name: 'Port of Spain' },
            { zone: '-05:00', type: 'Canonical', name: 'Port' },
            { zone: '-05:00', type: 'Alias', name: 'Porto Acre' },
            { zone: '-04:00', type: 'Canonical', name: 'Porto Velho' },
            { zone: '-04:00', type: 'Canonical', name: 'Puerto Rico' },
            { zone: '-03:00', type: 'Canonical', name: 'Punta Arenas' },
            { zone: '-06:00', type: 'Canonical', name: 'Rainy River' },
            { zone: '-06:00', type: 'Canonical', name: 'Rankin Inlet' },
            { zone: '-03:00', type: 'Canonical', name: 'Recife' },
            { zone: '-06:00', type: 'Canonical', name: 'Regina' },
            { zone: '-06:00', type: 'Canonical', name: 'Resolute' },
            { zone: '-05:00', type: 'Canonical', name: 'Rio Branco' },
            { zone: '-03:00', type: 'Alias', name: 'Rosario' },
            { zone: '-08:00', type: 'Alias', name: 'Santa Isabel' },
            { zone: '-03:00', type: 'Canonical', name: 'Santarem' },
            { zone: '-04:00', type: 'Canonical', name: 'Santiago' },
            { zone: '-04:00', type: 'Canonical', name: 'Santo Domingo' },
            { zone: '-03:00', type: 'Canonical', name: 'Sao Paulo' },
            { zone: '-01:00', type: 'Canonical', name: 'Scoresbysund' },
            { zone: '-07:00', type: 'Alias', name: 'Shiprock' },
            { zone: '-09:00', type: 'Canonical', name: 'Sitka' },
            { zone: '-04:00', type: 'Alias', name: 'St Barthelemy' },
            { zone: '-03:30', type: 'Canonical', name: 'St Johns' },
            { zone: '-04:00', type: 'Alias', name: 'St Kitts' },
            { zone: '-04:00', type: 'Alias', name: 'St Lucia' },
            { zone: '-04:00', type: 'Alias', name: 'St Thomas' },
            { zone: '-04:00', type: 'Alias', name: 'St Vincent' },
            { zone: '-06:00', type: 'Canonical', name: 'Swift Current' },
            { zone: '-06:00', type: 'Canonical', name: 'Tegucigalpa' },
            { zone: '-04:00', type: 'Canonical', name: 'Thule' },
            { zone: '-05:00', type: 'Canonical', name: 'Thunder Bay' },
            { zone: '-08:00', type: 'Canonical', name: 'Tijuana' },
            { zone: '-05:00', type: 'Canonical', name: 'Toronto' },
            { zone: '-04:00', type: 'Alias', name: 'Tortola' },
            { zone: '-08:00', type: 'Canonical', name: 'Vancouver' },
            { zone: '-04:00', type: 'Alias', name: 'Virgin' },
            { zone: '-08:00', type: 'Canonical', name: 'Whitehorse' },
            { zone: '-06:00', type: 'Canonical', name: 'Winnipeg' },
            { zone: '-09:00', type: 'Canonical', name: 'Yakutat' },
            { zone: '-07:00', type: 'Canonical', name: 'Yellowknife' },
        ]
    },
    {
        name: 'Antarctica',
        zones: [
            { zone: '+11:00', type: 'Canonical', name: 'Casey' },
            { zone: '+07:00', type: 'Canonical', name: 'Davis' },
            { zone: '+10:00', type: 'Canonical', name: 'DumontDUrville' },
            { zone: '+11:00', type: 'Canonical', name: 'Macquarie' },
            { zone: '+05:00', type: 'Canonical', name: 'Mawson' },
            { zone: '+12:00', type: 'Alias', name: 'McMurdo' },
            { zone: '-03:00', type: 'Canonical', name: 'Palmer' },
            { zone: '-03:00', type: 'Canonical', name: 'Rothera' },
            { zone: '+12:00', type: 'Alias', name: 'South Pole' },
            { zone: '+03:00', type: 'Canonical', name: 'Syowa' },
            { zone: '+00:00', type: 'Canonical', name: 'Troll' },
            { zone: '+06:00', type: 'Canonical', name: 'Vostok' },
        ]
    },
    {
        name: 'Arctic',
        zones: [
            { zone: '+01:00', type: 'Alias', name: 'Longyearbyen' },
        ]
    },
    {
        name: 'Asia',
        zones: [
            { zone: '+03:00', type: 'Alias', name: 'Aden' },
            { zone: '+06:00', type: 'Canonical', name: 'Almaty' },
            { zone: '+02:00', type: 'Canonical', name: 'Amman' },
            { zone: '+12:00', type: 'Canonical', name: 'Anadyr' },
            { zone: '+05:00', type: 'Canonical', name: 'Aqtau' },
            { zone: '+05:00', type: 'Canonical', name: 'Aqtobe' },
            { zone: '+05:00', type: 'Canonical', name: 'Ashgabat' },
            { zone: '+05:00', type: 'Alias', name: 'Ashkhabad' },
            { zone: '+05:00', type: 'Canonical', name: 'Atyrau' },
            { zone: '+03:00', type: 'Canonical', name: 'Baghdad' },
            { zone: '+03:00', type: 'Alias', name: 'Bahrain' },
            { zone: '+04:00', type: 'Canonical', name: 'Baku' },
            { zone: '+07:00', type: 'Canonical', name: 'Bangkok' },
            { zone: '+07:00', type: 'Canonical', name: 'Barnaul' },
            { zone: '+02:00', type: 'Canonical', name: 'Beirut' },
            { zone: '+06:00', type: 'Canonical', name: 'Bishkek' },
            { zone: '+08:00', type: 'Canonical', name: 'Brunei' },
            { zone: '+05:30', type: 'Alias', name: 'Calcutta' },
            { zone: '+09:00', type: 'Canonical', name: 'Chita' },
            { zone: '+08:00', type: 'Canonical', name: 'Choibalsan' },
            { zone: '+08:00', type: 'Alias', name: 'Chongqing' },
            { zone: '+08:00', type: 'Alias', name: 'Chungking' },
            { zone: '+05:30', type: 'Canonical', name: 'Colombo' },
            { zone: '+06:00', type: 'Alias', name: 'Dacca' },
            { zone: '+02:00', type: 'Canonical', name: 'Damascus' },
            { zone: '+06:00', type: 'Canonical', name: 'Dhaka' },
            { zone: '+09:00', type: 'Canonical', name: 'Dili' },
            { zone: '+04:00', type: 'Canonical', name: 'Dubai' },
            { zone: '+05:00', type: 'Canonical', name: 'Dushanbe' },
            { zone: '+02:00', type: 'Canonical', name: 'Famagusta' },
            { zone: '+02:00', type: 'Canonical', name: 'Gaza' },
            { zone: '+08:00', type: 'Alias', name: 'Harbin' },
            { zone: '+02:00', type: 'Canonical', name: 'Hebron' },
            { zone: '+07:00', type: 'Canonical', name: 'Ho Chi Minh' },
            { zone: '+08:00', type: 'Canonical', name: 'Hong Kong' },
            { zone: '+07:00', type: 'Canonical', name: 'Hovd' },
            { zone: '+08:00', type: 'Canonical', name: 'Irkutsk' },
            { zone: '+03:00', type: 'Alias', name: 'Istanbul' },
            { zone: '+07:00', type: 'Canonical', name: 'Jakarta' },
            { zone: '+09:00', type: 'Canonical', name: 'Jayapura' },
            { zone: '+02:00', type: 'Canonical', name: 'Jerusalem' },
            { zone: '+04:30', type: 'Canonical', name: 'Kabul' },
            { zone: '+12:00', type: 'Canonical', name: 'Kamchatka' },
            { zone: '+05:00', type: 'Canonical', name: 'Karachi' },
            { zone: '+06:00', type: 'Alias', name: 'Kashgar' },
            { zone: '+05:45', type: 'Canonical', name: 'Kathmandu' },
            { zone: '+05:45', type: 'Alias', name: 'Katmandu' },
            { zone: '+09:00', type: 'Canonical', name: 'Khandyga' },
            { zone: '+05:30', type: 'Canonical', name: 'Kolkata' },
            { zone: '+07:00', type: 'Canonical', name: 'Krasnoyarsk' },
            { zone: '+08:00', type: 'Canonical', name: 'Kuala Lumpur' },
            { zone: '+08:00', type: 'Canonical', name: 'Kuching' },
            { zone: '+03:00', type: 'Alias', name: 'Kuwait' },
            { zone: '+08:00', type: 'Alias', name: 'Macao' },
            { zone: '+08:00', type: 'Canonical', name: 'Macau' },
            { zone: '+11:00', type: 'Canonical', name: 'Magadan' },
            { zone: '+08:00', type: 'Canonical', name: 'Makassar' },
            { zone: '+08:00', type: 'Canonical', name: 'Manila' },
            { zone: '+04:00', type: 'Alias', name: 'Muscat' },
            { zone: '+02:00', type: 'Canonical', name: 'Nicosia' },
            { zone: '+07:00', type: 'Canonical', name: 'Novokuznetsk' },
            { zone: '+07:00', type: 'Canonical', name: 'Novosibirsk' },
            { zone: '+06:00', type: 'Canonical', name: 'Omsk' },
            { zone: '+05:00', type: 'Canonical', name: 'Oral' },
            { zone: '+07:00', type: 'Alias', name: 'Phnom Penh' },
            { zone: '+07:00', type: 'Canonical', name: 'Pontianak' },
            { zone: '+09:00', type: 'Canonical', name: 'Pyongyang' },
            { zone: '+03:00', type: 'Canonical', name: 'Qatar' },
            { zone: '+05:00', type: 'Canonical', name: 'Qyzylorda' },
            { zone: '+06:30', type: 'Alias', name: 'Rangoon' },
            { zone: '+03:00', type: 'Canonical', name: 'Riyadh' },
            { zone: '+07:00', type: 'Alias', name: 'Saigon' },
            { zone: '+11:00', type: 'Canonical', name: 'Sakhalin' },
            { zone: '+05:00', type: 'Canonical', name: 'Samarkand' },
            { zone: '+09:00', type: 'Canonical', name: 'Seoul' },
            { zone: '+08:00', type: 'Canonical', name: 'Shanghai' },
            { zone: '+08:00', type: 'Canonical', name: 'Singapore' },
            { zone: '+11:00', type: 'Canonical', name: 'Srednekolymsk' },
            { zone: '+08:00', type: 'Canonical', name: 'Taipei' },
            { zone: '+05:00', type: 'Canonical', name: 'Tashkent' },
            { zone: '+04:00', type: 'Canonical', name: 'Tbilisi' },
            { zone: '+03:30', type: 'Canonical', name: 'Tehran' },
            { zone: '+02:00', type: 'Alias', name: 'Tel Aviv' },
            { zone: '+06:00', type: 'Alias', name: 'Thimbu' },
            { zone: '+06:00', type: 'Canonical', name: 'Thimphu' },
            { zone: '+09:00', type: 'Canonical', name: 'Tokyo' },
            { zone: '+07:00', type: 'Canonical', name: 'Tomsk' },
            { zone: '+08:00', type: 'Alias', name: 'Ujung Pandang' },
            { zone: '+08:00', type: 'Canonical', name: 'Ulaanbaatar' },
            { zone: '+08:00', type: 'Alias', name: 'Ulan Bator' },
            { zone: '+06:00', type: 'Canonical', name: 'Urumqi' },
            { zone: '+10:00', type: 'Canonical', name: 'Ust' },
            { zone: '+07:00', type: 'Alias', name: 'Vientiane' },
            { zone: '+10:00', type: 'Canonical', name: 'Vladivostok' },
            { zone: '+09:00', type: 'Canonical', name: 'Yakutsk' },
            { zone: '+06:30', type: 'Canonical', name: 'Yangon' },
            { zone: '+05:00', type: 'Canonical', name: 'Yekaterinburg' },
            { zone: '+04:00', type: 'Canonical', name: 'Yerevan' },
        ]
    },
    {
        name: 'Atlantic',
        zones: [
            { zone: '-01:00', type: 'Canonical', name: 'Azores' },
            { zone: '-04:00', type: 'Canonical', name: 'Bermuda' },
            { zone: '+00:00', type: 'Canonical', name: 'Canary' },
            { zone: '-01:00', type: 'Canonical', name: 'Cape Verde' },
            { zone: '+00:00', type: 'Alias', name: 'Faeroe' },
            { zone: '+00:00', type: 'Canonical', name: 'Faroe' },
            { zone: '+01:00', type: 'Alias', name: 'Jan Mayen' },
            { zone: '+00:00', type: 'Canonical', name: 'Madeira' },
            { zone: '+00:00', type: 'Canonical', name: 'Reykjavik' },
            { zone: '-02:00', type: 'Canonical', name: 'South Georgia' },
            { zone: '+00:00', type: 'Alias', name: 'St Helena' },
            { zone: '-03:00', type: 'Canonical', name: 'Stanley' },
        ]
    },
    {
        name: 'Australia',
        zones: [
            { zone: '+09:30', type: 'Canonical', name: 'Adelaide' },
            { zone: '+10:00', type: 'Canonical', name: 'Brisbane' },
            { zone: '+09:30', type: 'Canonical', name: 'Broken Hill' },
            { zone: '+10:00', type: 'Alias', name: 'Canberra' },
            { zone: '+10:00', type: 'Canonical', name: 'Currie' },
            { zone: '+09:30', type: 'Canonical', name: 'Darwin' },
            { zone: '+08:45', type: 'Canonical', name: 'Eucla' },
            { zone: '+10:00', type: 'Canonical', name: 'Hobart' },
            { zone: '+10:00', type: 'Canonical', name: 'Lindeman' },
            { zone: '+10:30', type: 'Canonical', name: 'Lord Howe' },
            { zone: '+10:00', type: 'Canonical', name: 'Melbourne' },
            { zone: '+08:00', type: 'Canonical', name: 'Perth' },
            { zone: '+10:00', type: 'Canonical', name: 'Sydney' },
            { zone: '+09:30', type: 'Alias', name: 'Yancowinna' },
        ]
    },
    {
        name: 'Europe',
        zones: [
            { zone: '+01:00', type: 'Canonical', name: 'Amsterdam' },
            { zone: '+01:00', type: 'Canonical', name: 'Andorra' },
            { zone: '+04:00', type: 'Canonical', name: 'Astrakhan' },
            { zone: '+02:00', type: 'Canonical', name: 'Athens' },
            { zone: '+00:00', type: 'Alias', name: 'Belfast' },
            { zone: '+01:00', type: 'Canonical', name: 'Belgrade' },
            { zone: '+01:00', type: 'Canonical', name: 'Berlin' },
            { zone: '+01:00', type: 'Alias', name: 'Bratislava' },
            { zone: '+01:00', type: 'Canonical', name: 'Brussels' },
            { zone: '+02:00', type: 'Canonical', name: 'Bucharest' },
            { zone: '+01:00', type: 'Canonical', name: 'Budapest' },
            { zone: '+01:00', type: 'Alias', name: 'Busingen' },
            { zone: '+02:00', type: 'Canonical', name: 'Chisinau' },
            { zone: '+01:00', type: 'Canonical', name: 'Copenhagen' },
            { zone: '+00:00', type: 'Canonical', name: 'Dublin' },
            { zone: '+01:00', type: 'Canonical', name: 'Gibraltar' },
            { zone: '+00:00', type: 'Alias', name: 'Guernsey' },
            { zone: '+02:00', type: 'Canonical', name: 'Helsinki' },
            { zone: '+00:00', type: 'Alias', name: 'Isle of Man' },
            { zone: '+03:00', type: 'Canonical', name: 'Istanbul' },
            { zone: '+00:00', type: 'Alias', name: 'Jersey' },
            { zone: '+02:00', type: 'Canonical', name: 'Kaliningrad' },
            { zone: '+02:00', type: 'Canonical', name: 'Kiev' },
            { zone: '+03:00', type: 'Canonical', name: 'Kirov' },
            { zone: '+00:00', type: 'Canonical', name: 'Lisbon' },
            { zone: '+01:00', type: 'Alias', name: 'Ljubljana' },
            { zone: '+00:00', type: 'Canonical', name: 'London' },
            { zone: '+01:00', type: 'Canonical', name: 'Luxembourg' },
            { zone: '+01:00', type: 'Canonical', name: 'Madrid' },
            { zone: '+01:00', type: 'Canonical', name: 'Malta' },
            { zone: '+02:00', type: 'Alias', name: 'Mariehamn' },
            { zone: '+03:00', type: 'Canonical', name: 'Minsk' },
            { zone: '+01:00', type: 'Canonical', name: 'Monaco' },
            { zone: '+03:00', type: 'Canonical', name: 'Moscow' },
            { zone: '+01:00', type: 'Canonical', name: 'Oslo' },
            { zone: '+01:00', type: 'Canonical', name: 'Paris' },
            { zone: '+01:00', type: 'Alias', name: 'Podgorica' },
            { zone: '+01:00', type: 'Canonical', name: 'Prague' },
            { zone: '+02:00', type: 'Canonical', name: 'Riga' },
            { zone: '+01:00', type: 'Canonical', name: 'Rome' },
            { zone: '+04:00', type: 'Canonical', name: 'Samara' },
            { zone: '+01:00', type: 'Alias', name: 'San Marino' },
            { zone: '+01:00', type: 'Alias', name: 'Sarajevo' },
            { zone: '+04:00', type: 'Canonical', name: 'Saratov' },
            { zone: '+03:00', type: 'Canonical', name: 'Simferopol' },
            { zone: '+01:00', type: 'Alias', name: 'Skopje' },
            { zone: '+02:00', type: 'Canonical', name: 'Sofia' },
            { zone: '+01:00', type: 'Canonical', name: 'Stockholm' },
            { zone: '+02:00', type: 'Canonical', name: 'Tallinn' },
            { zone: '+01:00', type: 'Canonical', name: 'Tirane' },
            { zone: '+02:00', type: 'Alias', name: 'Tiraspol' },
            { zone: '+04:00', type: 'Canonical', name: 'Ulyanovsk' },
            { zone: '+02:00', type: 'Canonical', name: 'Uzhgorod' },
            { zone: '+01:00', type: 'Alias', name: 'Vaduz' },
            { zone: '+01:00', type: 'Alias', name: 'Vatican' },
            { zone: '+01:00', type: 'Canonical', name: 'Vienna' },
            { zone: '+02:00', type: 'Canonical', name: 'Vilnius' },
            { zone: '+04:00', type: 'Canonical', name: 'Volgograd' },
            { zone: '+01:00', type: 'Canonical', name: 'Warsaw' },
            { zone: '+01:00', type: 'Alias', name: 'Zagreb' },
            { zone: '+02:00', type: 'Canonical', name: 'Zaporozhye' },
            { zone: '+01:00', type: 'Canonical', name: 'Zurich' },
        ]
    },
    {
        name: 'Indian',
        zones: [
            { zone: '+03:00', type: 'Alias', name: 'Antananarivo' },
            { zone: '+06:00', type: 'Canonical', name: 'Chagos' },
            { zone: '+07:00', type: 'Canonical', name: 'Christmas' },
            { zone: '+06:30', type: 'Canonical', name: 'Cocos' },
            { zone: '+03:00', type: 'Alias', name: 'Comoro' },
            { zone: '+05:00', type: 'Canonical', name: 'Kerguelen' },
            { zone: '+04:00', type: 'Canonical', name: 'Mahe' },
            { zone: '+05:00', type: 'Canonical', name: 'Maldives' },
            { zone: '+04:00', type: 'Canonical', name: 'Mauritius' },
            { zone: '+03:00', type: 'Alias', name: 'Mayotte' },
            { zone: '+04:00', type: 'Canonical', name: 'Reunion' },
        ]
    },
    {
        name: 'Pacific',
        zones: [
            { zone: '+13:00', type: 'Canonical', name: 'Apia' },
            { zone: '+12:00', type: 'Canonical', name: 'Auckland' },
            { zone: '+11:00', type: 'Canonical', name: 'Bougainville' },
            { zone: '+12:45', type: 'Canonical', name: 'Chatham' },
            { zone: '+10:00', type: 'Canonical', name: 'Chuuk' },
            { zone: '-06:00', type: 'Canonical', name: 'Easter' },
            { zone: '+11:00', type: 'Canonical', name: 'Efate' },
            { zone: '+13:00', type: 'Canonical', name: 'Enderbury' },
            { zone: '+13:00', type: 'Canonical', name: 'Fakaofo' },
            { zone: '+12:00', type: 'Canonical', name: 'Fiji' },
            { zone: '+12:00', type: 'Canonical', name: 'Funafuti' },
            { zone: '-06:00', type: 'Canonical', name: 'Galapagos' },
            { zone: '-09:00', type: 'Canonical', name: 'Gambier' },
            { zone: '+11:00', type: 'Canonical', name: 'Guadalcanal' },
            { zone: '+10:00', type: 'Canonical', name: 'Guam' },
            { zone: '-10:00', type: 'Canonical', name: 'Honolulu' },
            { zone: '-10:00', type: 'Alias', name: 'Johnston' },
            { zone: '+14:00', type: 'Canonical', name: 'Kiritimati' },
            { zone: '+11:00', type: 'Canonical', name: 'Kosrae' },
            { zone: '+12:00', type: 'Canonical', name: 'Kwajalein' },
            { zone: '+12:00', type: 'Canonical', name: 'Majuro' },
            { zone: '-09:30', type: 'Canonical', name: 'Marquesas' },
            { zone: '-11:00', type: 'Alias', name: 'Midway' },
            { zone: '+12:00', type: 'Canonical', name: 'Nauru' },
            { zone: '-11:00', type: 'Canonical', name: 'Niue' },
            { zone: '+11:00', type: 'Canonical', name: 'Norfolk' },
            { zone: '+11:00', type: 'Canonical', name: 'Noumea' },
            { zone: '-11:00', type: 'Canonical', name: 'Pago Pago' },
            { zone: '+09:00', type: 'Canonical', name: 'Palau' },
            { zone: '-08:00', type: 'Canonical', name: 'Pitcairn' },
            { zone: '+11:00', type: 'Canonical', name: 'Pohnpei' },
            { zone: '+11:00', type: 'Alias', name: 'Ponape' },
            { zone: '+10:00', type: 'Canonical', name: 'Port Moresby' },
            { zone: '-10:00', type: 'Canonical', name: 'Rarotonga' },
            { zone: '+10:00', type: 'Alias', name: 'Saipan' },
            { zone: '-11:00', type: 'Alias', name: 'Samoa' },
            { zone: '-10:00', type: 'Canonical', name: 'Tahiti' },
            { zone: '+12:00', type: 'Canonical', name: 'Tarawa' },
            { zone: '+13:00', type: 'Canonical', name: 'Tongatapu' },
            { zone: '+10:00', type: 'Alias', name: 'Truk' },
            { zone: '+12:00', type: 'Canonical', name: 'Wake' },
            { zone: '+12:00', type: 'Canonical', name: 'Wallis' },
            { zone: '+10:00', type: 'Alias', name: 'Yap' },
        ]
    },
    {
        name: 'UTC',
        zones: [
            { zone: '+00:00', type: 'Alias', name: 'UTC Time' },
        ]
    },
    {
        name: 'GMT',
        zones: [
            { zone: '+00:00', type: 'Alias', name: 'GMT Time' },
        ]
    },
    {
        name: 'ETC',
        zones: [
            { zone: '+00:00', type: 'Canonical', name: 'GMT Time' },
            { zone: '+00:00', type: 'Canonical', name: 'UTC Time' },
        ]
    },
];
