export const Category = {
    ACTION: 'action',
    ALERT: 'alert',
    AV: 'av',
    COMMUNICATION: 'communication',
    CONTENT: 'content',
    DEVICE: 'device',
    EDITOR: 'editor',
    FILE: 'file',
    HARDWARE: 'hardware',
    IMAGE: 'image',
    MAPS: 'maps',
    NAVIGATION: 'navigation',
    NOTIFICATION: 'notification',
    PLACES: 'places',
    SOCIAL: 'social',
    TOGGLE: 'toggle',
};
