name: CI/CD

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]

env:
  GCE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  GCE_USER: interimproj
  GCE_INSTANCE: ubuntu-server-4
  GCE_INSTANCE_ZONE: europe-west2-c
  VM_DIST_PATH: /var/www/nean.io
  TEST_URL: https://nean.io/

jobs:
  build:
    name: Setup, Audit, Lint and Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 12.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: npm ci

    - name: NPM Audit
      run: npm audit

    - name: TSLint
      run: npm run lint

    - name: Build Angular client, Node API server and Borker worker
      run: npm run build

    - name: Save production artifacts
      uses: actions/upload-artifact@v1
      if: matrix.node-version == '12.x' && matrix.os == 'ubuntu-latest'
      with:
        name: dist
        path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ env.GCE_PROJECT_ID }}
        service_account_key: ${{ env.GCE_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Download dist
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: Rename dist to newdist
      run: mv dist newdist

    - name: Copy newdist to VM
      run: gcloud compute scp --recurse --zone=$GCE_INSTANCE_ZONE newdist $GCE_USER@$GCE_INSTANCE:$VM_DIST_PATH

    - name: Use newdist + pm2 reload
      run: gcloud compute ssh --zone=$GCE_INSTANCE_ZONE $GCE_USER@$GCE_INSTANCE --command "mv $VM_DIST_PATH/dist $VM_DIST_PATH/olddist && mv $VM_DIST_PATH/newdist $VM_DIST_PATH/dist && rm -rf $VM_DIST_PATH/olddist && export PATH=$PATH:/home/interimproj/.nvm/versions/node/v10.13.0/bin; pm2 reload all"

  test:
    name: Regression Testing
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
    - name: Lighthouse CI
      uses: treosh/lighthouse-ci-action@v3
      with:
        urls: |
          $TEST_URL
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage